"""add Email

Revision ID: 54348057c39f
Revises: 91ec78db8a71
Create Date: 2025-11-03 19:06:49.231741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54348057c39f'
down_revision: Union[str, Sequence[str], None] = '91ec78db8a71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_statuses', sa.Column('hex', sa.String(length=7), nullable=True))
    op.add_column('task_statuses', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('task_statuses', 'order')
    op.drop_column('task_statuses', 'hex')
    # ### end Alembic commands ###
