"""LEad

Revision ID: 6898eececc98
Revises: 49b1f7d3b2bf
Create Date: 2025-11-01 17:56:46.312022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6898eececc98'
down_revision: Union[str, Sequence[str], None] = '49b1f7d3b2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('leads', sa.Column('status_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.create_foreign_key(None, 'leads', 'lead_statuses', ['status_id'], ['id'], ondelete='SET NULL')
    op.drop_column('leads', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('status', postgresql.ENUM('NEW', 'PROCESSING', 'CANCELLED', 'DEAL', name='statusenum'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.drop_column('leads', 'status_id')
    op.drop_table('lead_statuses')
    # ### end Alembic commands ###
