"""Task Status

Revision ID: 7fa5801f9986
Revises: 99014df7e9fb
Create Date: 2025-10-31 19:50:54.168105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa5801f9986'
down_revision: Union[str, Sequence[str], None] = '99014df7e9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'task_statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
