"""lead Status

Revision ID: 8891bfa77d52
Revises: 54348057c39f
Create Date: 2025-11-06 18:07:51.336492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8891bfa77d52'
down_revision: Union[str, Sequence[str], None] = '54348057c39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lead_statuses_level_key'), 'lead_statuses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('lead_statuses_level_key'), 'lead_statuses', ['level'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
