"""User

Revision ID: 91ec78db8a71
Revises: 6898eececc98
Create Date: 2025-11-01 21:28:23.377318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ec78db8a71'
down_revision: Union[str, Sequence[str], None] = '6898eececc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_statuses', sa.Column('hex', sa.String(length=7), nullable=True))
    op.add_column('lead_statuses', sa.Column('level', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'lead_statuses', ['level'])
    op.add_column('users', sa.Column('role_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_constraint(None, 'lead_statuses', type_='unique')
    op.drop_column('lead_statuses', 'level')
    op.drop_column('lead_statuses', 'hex')
    # ### end Alembic commands ###
