"""Updated Lead Status

Revision ID: fdbe516d8400
Revises: 596c6eff6352
Create Date: 2025-11-09 16:39:54.019171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdbe516d8400'
down_revision: Union[str, Sequence[str], None] = '596c6eff6352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_statuses', 'deleted_at')
    op.drop_column('lead_statuses', 'created_at')
    op.drop_column('lead_statuses', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_statuses', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('lead_statuses', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('lead_statuses', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
