"""Added Lead File

Revision ID: 36385fe42255
Revises: fdbe516d8400
Create Date: 2025-11-09 20:33:45.570608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36385fe42255'
down_revision: Union[str, Sequence[str], None] = 'fdbe516d8400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_files_id'), 'lead_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_files_id'), table_name='lead_files')
    op.drop_table('lead_files')
    # ### end Alembic commands ###
