"""Added Lead Status bools

Revision ID: 596c6eff6352
Revises: f454260d5eb2
Create Date: 2025-11-07 19:45:23.157156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596c6eff6352'
down_revision: Union[str, Sequence[str], None] = 'f454260d5eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_statuses', sa.Column('can_delete', sa.Boolean(), nullable=True))
    op.add_column('lead_statuses', sa.Column('can_edit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # 2️⃣ Обновляем старые записи — ставим False по умолчанию
    op.execute("UPDATE lead_statuses SET can_delete = TRUE, can_edit = TRUE;")

    # 3️⃣ Теперь делаем поля NOT NULL + default (чтобы новые строки имели дефолты)
    op.alter_column('lead_statuses', 'can_delete',
                    existing_type=sa.Boolean(),
                    nullable=False,
                    server_default=sa.text('FALSE'))
    op.alter_column('lead_statuses', 'can_edit',
                    existing_type=sa.Boolean(),
                    nullable=False,
                    server_default=sa.text('TRUE'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_statuses', 'can_edit')
    op.drop_column('lead_statuses', 'can_delete')
    # ### end Alembic commands ###
